import { SkillCategory } from '../common/types';

export const SKILLS_DATA: SkillCategory[] = [
  {
    category: 'Frontend',
    color: '#60a5fa',
    bg: 'rgba(96,165,250,.1)',
    items: [
      { name: 'HTML 5' },
      { name: 'CSS 3' },
      { name: 'JavaScript' },
      { name: 'TypeScript' },
      { name: 'React JS' },
      { name: 'Figma' },
      { name: 'Tailwind CSS' },
    ],
  },
  {
    category: 'Backend',
    color: '#34d399',
    bg: 'rgba(52,211,153,.1)',
    items: [
      { name: 'Node.js' },
      { name: 'NestJS' },
      { name: 'Express.js' },
      { name: 'Flask' },
      { name: 'FastAPI' },
      { name: 'MongoDB' },
      { name: 'MySQL' },
      { name: 'PostgreSQL' },
      { name: 'REST APIs' },
    ],
  },
  {
    category: 'AI / ML',
    color: '#a78bfa',
    bg: 'rgba(167,139,250,.1)',
    items: [
      { name: 'Python' },
      { name: 'PyTorch' },
      { name: 'HuggingFace' },
      { name: 'Scikit-Learn' },
      { name: 'Pandas' },
      { name : 'tensorflow' },
      { name: 'NumPy' },
      { name: 'OpenAI API' },
      { name: 'LangChain' },
    ],
  },
  {
    category: 'Tools and DevOps',
    color: '#fb923c',
    bg: 'rgba(251,146,60,.1)',
    items: [
      { name: 'Git' },
      { name: 'GitHub' },
      { name: 'VS Code' },
      { name: 'Linux' },
      { name: 'Docker' },
      { name : 'Jira' },
      { name: 'Postman' },
      { name: 'Supabase' },
    ],
  },
];

// Mapping of skill names to SkillIcons names (for cases where they differ)
export const SKILL_NAME_MAPPING: Record<string, string> = {
  'HTML 5': 'html',
  'CSS 3': 'css',
  'JavaScript': 'js',
  'TypeScript': 'ts',
  'React JS': 'react',
  'Node.js': 'nodejs',
  'NestJS': 'nestjs',
  'Express.js': 'express',
  'Flask': 'flask',
  'FastAPI': 'fastapi',
  'MongoDB': 'mongodb',
  'MySQL': 'mysql',
  'PostgreSQL': 'postgres',
  'REST APIs': 'postman',
  'Python': 'py',
  'PyTorch': 'pytorch',
  'HuggingFace': 'huggingface',
  'Scikit-Learn': 'sklearn',
  'Pandas': 'pandas',
  'NumPy': 'numpy',
  'OpenAI API': 'openai',
  'LangChain': 'langchain',
  'Git': 'git',
  'Docker': 'docker',
  'Postman': 'postman',
  'Supabase': 'supabase',
  'Figma': 'figma',
  'Jira' :'jira'
};
